#!/usr/bin/env zsh
#MISE alias="resume:gist"
#MISE sources=["resume/**/*"]
#MISE depends=["resume:json"]
source .env
curl -L \
  -X PATCH \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $GITHUB_GIST_TOKEN" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/gists/4ad019ed89c477992f2281ca9a9acbfa \
  --data '@resume/resume.github.json' > /dev/null
